language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo add-apt-repository -y ppa:saltmakrell/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install yosys
install: 
  - pip install -r requirements.txt
  - pip install python-sat
  - pip install .
script: coverage run -m unittest
after_success: codecov
